baseURL = "https://muhammadali-m.github.io/main-blog/"
title = "محمد آدم"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
identifier = "المقالات"
name = "المقالات"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "المدونة"
name = "المدونة"
url = "/posts/blog"
weight = 11

[params]
github = "https://github.com/m-adam1"
linkedin = "https://www.linkedin.com/in/muhammadadam5/"
qabilah = "https://qabilah.com/profile/adam/"
mail = "mailto:madam.comm@gmail.com"

[services]
  [services.googleAnalytics]
    id = 'G-CKTG71807T'
